#ifndef PHOTOPLANNER_GLOBAL_H
#define PHOTOPLANNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHOTOPLANNER_LIBRARY)
#  define PHOTOPLANNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHOTOPLANNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHOTOPLANNER_GLOBAL_H
